### ISSUE TITLE
Write a System Requirements Specification

### ISSUE THREAD

**Issue by MizuGuenHoan** [caodaithanhthe/caodaithanhthe.github.io#1]
Write a System Requirements Specification base the attachment:
[SDL-TL-102 - Software Requirements Specification.docx](https://github.com/caodaithanhthe/caodaithanhthe.github.io/files/3991014/SDL-TL-102.-.Software.Requirements.Specification.docx)

**Comment by MizuGuenHoan** [comment]
I'll create that file

**Comment by caodaithanhthe** [comment]
Dear Mizu,

OK, if you for more info, just mail to me, I'll answer all of your questions 

Thank You
CDTT

**Comment by MizuGuenHoan** [comment]
OK

**Comment by MizuGuenHoan** [comment]
Dear CDTT,

I think you should config the project dashboard

Thanks & best regards.
Mizu Guen Hoan

**Comment by MizuGuenHoan** [comment]
Dear @caodaithanhthe ,

I think you should config the project dashboard

Thanks & best regards.
Mizu Guen Hoan

**Comment by caodaithanhthe** [comment]
> Dear @caodaithanhthe ,
> 
> I think you should config the project dashboard
> 
> Thanks & best regards.
> Mizu Guen Hoan

OK 
I'll do it
