### ISSUE TITLE
Add more member for this project

### ISSUE THREAD

**Issue by caodaithanhthe** [caodaithanhthe/caodaithanhthe.github.io#2]
Dear Mizu,

I will invite a new member for you to help you done this project for me.

Thanks
CDTT

**Comment by MizuGuenHoan** [comment]
Dear CDTT,

Ok

Thanks & best regards,
Mizu Guen Hoan

**Comment by nhanntdl** [comment]
Dear All,

Hello, My name is Nguyen Trung Nhan, 
I'll help you to do this project

Thanks & best regards,
Nhan Nguyen Trung
