### ISSUE TITLE
Create a Social preview card

### ISSUE THREAD

**Issue by caodaithanhthe** [caodaithanhthe/caodaithanhthe.github.io#3]
Dear All,

I need a Social preview card for this project, please help me create it

Thanks
CDTT

**Comment by MizuGuenHoan** [comment]
Dear CDTT,

I think you should assign to @nhanntdl because he is a designer 

Thanks & best regards,
Mizu Guen Hoan

**Comment by nhanntdl** [comment]
Dear All, 

I can do it for us

Thanks & best regards

**Comment by caodaithanhthe** [comment]
OK I'll assign to @nhanntdl 
Thanks for your suggestions @MizuGuenHoan
