### ISSUE TITLE
Roles Definiton

### ISSUE THREAD

**Issue by MizuGuenHoan** [caodaithanhthe/caodaithanhthe.github.io#4]
Dear All, 

Right now, we need to identify the role of each person in this project that relies on the scrum model

1. Product Owner:  @caodaithanhthe 
2. Scrum Master: @MizuGuenHoan 
3: Scrum Tem: @MizuGuenHoan , @nhanntdl 
Do you have any questions?

Thanks & best regards,
Mizu Guen Hoan

**Comment by nhanntdl** [comment]
I agree

**Comment by caodaithanhthe** [comment]
I agree

**Comment by MizuGuenHoan** [comment]
I agree

**Comment by MizuGuenHoan** [comment]
Ok, for the following role, I need @caodaithanhthe help me create an SRS file because you are a product owner

**Comment by caodaithanhthe** [comment]
ok

**Comment by MizuGuenHoan** [comment]
Dear All,

OK, I'll close this issue with all of you agree

Thanks & Best Regards
Mizu Guen Hoan
