### ISSUE TITLE
Additional development team members

### ISSUE THREAD

**Issue by caodaithanhthe** [caodaithanhthe/caodaithanhthe.github.io#5]
# Additional development team members

> To do the best for this project, we need a talented team with đeicated and passionate members

**Comment by caodaithanhthe** [comment]
Dear All, 

I have just added you to my project (@MizuGuenHoan  and @nhanntdl ), 
Introduce yourself and especially your strengths

Thanks.
CDTT

**Comment by MizuGuenHoan** [comment]
Hello All,

I'm Mizu Guen Hoan, I can do anything for you

Thanks & Best Regards
Mizu Guen Hoan

**Comment by nhanntdl** [comment]
Hi All,

My name is Nguyen Trung Nhan, I come from Vietnam,
I can do anything, but my best is design.

Thanks & best regards
Nhan Nguyen Trung

**Comment by caodaithanhthe** [comment]
Welcome @MizuGuenHoan and @nhanntdl 
The addition of members for the team has been completed, does anyone have any ideas?
If there are no comments. I will close this issue
