### ISSUE TITLE
Add member in this project

### ISSUE THREAD

**Issue by caodaithanhthe** [caodaithanhthe/caodaithanhthe.github.io#6]
Dear @MizuGuenHoan ,

I'll invite to here a member to help to do this project 

Thanks
CDTT

**Comment by MizuGuenHoan** [comment]
> Dear @MizuGuenHoan ,
> 
> I'll invite to here a member to help to do this project
> 
> Thanks
> CDTT

OK @caodaithanhthe 
Thanks
