### ISSUE TITLE
Find the best designer for customer

### ISSUE THREAD

**Issue by caodaithanhthe** [caodaithanhthe/caodaithanhthe.github.io#7]
Dear All,

We need the best designer for the customer,

Thanks
CDTT

**Comment by MizuGuenHoan** [comment]
I think @nhanntdl can do this work because he is a designer, he has the skills to do this job

**Comment by nhanntdl** [comment]
Dear All,

I'll take this job

Thanks & regards
Nhan Nguyen Trung

**Comment by caodaithanhthe** [comment]
OK

**Comment by caodaithanhthe** [comment]
Dear All,

With the approval of everyone,
@nhanntdl will undertake all the design work for this project

Thanks
CDTT
